# Generated by Django 5.2.6 on 2025-12-24 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="certification",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descricao"),
        ),
        migrations.AlterField(
            model_name="certification",
            name="issuer",
            field=models.CharField(blank=True, max_length=120, verbose_name="Emissor"),
        ),
        migrations.AlterField(
            model_name="certification",
            name="name",
            field=models.CharField(max_length=120, unique=True, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="certification",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Ativo"),
                    ("inactive", "Inativo"),
                    ("pending", "Pendente"),
                ],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="certification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
        migrations.AlterField(
            model_name="client",
            name="billing_cycle",
            field=models.CharField(
                choices=[
                    ("monthly", "Mensal"),
                    ("biweekly", "Quinzenal"),
                    ("weekly", "Semanal"),
                    ("on_demand", "Sob demanda"),
                ],
                default="monthly",
                max_length=20,
                verbose_name="Ciclo de faturamento",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="commercial_notes",
            field=models.TextField(blank=True, verbose_name="Observacoes comerciais"),
        ),
        migrations.AlterField(
            model_name="client",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients",
                to="cadastros.company",
                verbose_name="Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="contract_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fim do contrato"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="contract_start",
            field=models.DateField(
                blank=True, null=True, verbose_name="Inicio do contrato"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="client",
            name="payment_terms_days",
            field=models.PositiveSmallIntegerField(
                default=30, verbose_name="Prazo de pagamento (dias)"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Ativo"),
                    ("inactive", "Inativo"),
                    ("pending", "Pendente"),
                ],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
        migrations.AlterField(
            model_name="clientcontact",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="cadastros.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="clientcontact",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="clientcontact",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="clientcontact",
            name="is_primary",
            field=models.BooleanField(default=False, verbose_name="Contato principal"),
        ),
        migrations.AlterField(
            model_name="clientcontact",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="clientcontact",
            name="phone",
            field=models.CharField(blank=True, max_length=30, verbose_name="Telefone"),
        ),
        migrations.AlterField(
            model_name="clientcontact",
            name="role",
            field=models.CharField(blank=True, max_length=120, verbose_name="Cargo"),
        ),
        migrations.AlterField(
            model_name="clientcontact",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Ativo"),
                    ("inactive", "Inativo"),
                    ("pending", "Pendente"),
                ],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="clientcontact",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
        migrations.AlterField(
            model_name="company",
            name="address_line",
            field=models.CharField(blank=True, max_length=255, verbose_name="Endereco"),
        ),
        migrations.AlterField(
            model_name="company",
            name="billing_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email de faturamento"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("primary", "Empresa principal"),
                    ("branch", "Filial"),
                    ("client", "Cliente"),
                ],
                default="client",
                max_length=20,
                verbose_name="Tipo de empresa",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="country",
            field=models.CharField(default="BR", max_length=2, verbose_name="Pais"),
        ),
        migrations.AlterField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="company",
            name="legal_name",
            field=models.CharField(max_length=200, verbose_name="Razao social"),
        ),
        migrations.AlterField(
            model_name="company",
            name="municipal_registration",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="Inscricao municipal"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Observacoes"),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone",
            field=models.CharField(blank=True, max_length=30, verbose_name="Telefone"),
        ),
        migrations.AlterField(
            model_name="company",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, verbose_name="CEP"),
        ),
        migrations.AlterField(
            model_name="company",
            name="state",
            field=models.CharField(blank=True, max_length=100, verbose_name="Estado"),
        ),
        migrations.AlterField(
            model_name="company",
            name="state_registration",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="Inscricao estadual"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Ativo"),
                    ("inactive", "Inativo"),
                    ("pending", "Pendente"),
                ],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="tax_id",
            field=models.CharField(max_length=32, unique=True, verbose_name="CNPJ"),
        ),
        migrations.AlterField(
            model_name="company",
            name="trade_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nome fantasia"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
        migrations.AlterField(
            model_name="competency",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="competency",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descricao"),
        ),
        migrations.AlterField(
            model_name="competency",
            name="name",
            field=models.CharField(max_length=120, unique=True, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="competency",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Ativo"),
                    ("inactive", "Inativo"),
                    ("pending", "Pendente"),
                ],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="competency",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="certifications",
            field=models.ManyToManyField(
                blank=True,
                related_name="consultants",
                to="cadastros.certification",
                verbose_name="Certificacoes",
            ),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consultants",
                to="cadastros.company",
                verbose_name="Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="competencies",
            field=models.ManyToManyField(
                blank=True,
                related_name="consultants",
                to="cadastros.competency",
                verbose_name="Competencias",
            ),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="contract_type",
            field=models.CharField(
                choices=[("pj", "PJ"), ("pf", "PF")],
                default="pj",
                max_length=10,
                verbose_name="Tipo de contrato",
            ),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="document",
            field=models.CharField(blank=True, max_length=32, verbose_name="Documento"),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fim do contrato"
            ),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="full_name",
            field=models.CharField(max_length=200, verbose_name="Nome completo"),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Observacoes"),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="phone",
            field=models.CharField(blank=True, max_length=30, verbose_name="Telefone"),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Inicio do contrato"
            ),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Ativo"),
                    ("inactive", "Inativo"),
                    ("pending", "Pendente"),
                ],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
        migrations.AlterField(
            model_name="consultantrate",
            name="consultant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rates",
                to="cadastros.consultant",
                verbose_name="Consultor",
            ),
        ),
        migrations.AlterField(
            model_name="consultantrate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="consultantrate",
            name="currency",
            field=models.CharField(default="BRL", max_length=3, verbose_name="Moeda"),
        ),
        migrations.AlterField(
            model_name="consultantrate",
            name="end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fim da vigencia"
            ),
        ),
        migrations.AlterField(
            model_name="consultantrate",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Observacoes"),
        ),
        migrations.AlterField(
            model_name="consultantrate",
            name="rate",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Tarifa"
            ),
        ),
        migrations.AlterField(
            model_name="consultantrate",
            name="start_date",
            field=models.DateField(verbose_name="Inicio da vigencia"),
        ),
        migrations.AlterField(
            model_name="consultantrate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
    ]
