# Generated by Django 5.2.6 on 2025-12-24 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0003_phase_product_module_submodule"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeploymentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Descricao"),
                ),
                ("seq", models.PositiveSmallIntegerField(verbose_name="Seq")),
                (
                    "seq_predecessor",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Seq predecessora"
                    ),
                ),
                ("project", models.CharField(max_length=200, verbose_name="Projeto")),
                (
                    "activity",
                    models.CharField(max_length=200, verbose_name="Atividade"),
                ),
                (
                    "subactivity",
                    models.CharField(max_length=200, verbose_name="Subatividade"),
                ),
                ("planned_start", models.DateField(verbose_name="Inicio previsto")),
                ("planned_end", models.DateField(verbose_name="Final previsto")),
                ("days", models.PositiveSmallIntegerField(verbose_name="Dias")),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Horas"
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deployment_templates",
                        to="cadastros.module",
                        verbose_name="Modulo",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deployment_templates",
                        to="cadastros.phase",
                        verbose_name="Fase",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deployment_templates",
                        to="cadastros.product",
                        verbose_name="Produto",
                    ),
                ),
                (
                    "submodule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deployment_templates",
                        to="cadastros.submodule",
                        verbose_name="Submodulo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template de implantacao",
                "verbose_name_plural": "Templates de implantacao",
                "ordering": ("description", "seq"),
            },
        ),
    ]
