# Generated by Django 5.2.6 on 2025-12-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0004_deploymenttemplate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deploymenttemplate",
            name="planned_end",
        ),
        migrations.RemoveField(
            model_name="deploymenttemplate",
            name="planned_start",
        ),
    ]
