# Generated by Django 5.2.6 on 2025-12-24 13:56

import cadastros.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0005_remove_deploymenttemplate_planned_end_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=200, verbose_name="Descricao do projeto"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("budget", "Orcamento"),
                            ("implementation", "Em Implantacao"),
                            ("paused", "Paralizado"),
                            ("canceled", "Cancelado"),
                            ("completed", "Finalizado"),
                        ],
                        default="budget",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Valor total contratado (R$)",
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor hora (R$)"
                    ),
                ),
                (
                    "contracted_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Horas contratadas",
                    ),
                ),
                (
                    "contingency_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Contingencia (%)",
                    ),
                ),
                (
                    "available_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Horas disponiveis",
                    ),
                ),
                (
                    "available_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Valor disponivel (R$)",
                    ),
                ),
                (
                    "billing_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billing_projects",
                        to="cadastros.client",
                        verbose_name="Cliente de faturamento",
                    ),
                ),
                (
                    "client_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects_client_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario do cliente",
                    ),
                ),
                (
                    "external_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects_external",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="GP externo",
                    ),
                ),
                (
                    "internal_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects_internal",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="GP interno",
                    ),
                ),
                (
                    "project_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="cadastros.client",
                        verbose_name="Cliente do projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projeto",
                "verbose_name_plural": "Projetos",
            },
        ),
        migrations.CreateModel(
            name="ProjectAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[("scope", "Escopo"), ("other", "Outro")],
                        default="other",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Descricao do arquivo"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=cadastros.models._project_attachment_path,
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="cadastros.project",
                        verbose_name="Projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arquivo do projeto",
                "verbose_name_plural": "Arquivos do projeto",
            },
        ),
    ]
