# Generated by Django 5.2.6 on 2025-12-24 14:26

import cadastros.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0006_project_projectattachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultantAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Descricao do arquivo"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=cadastros.models._consultant_attachment_path,
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="cadastros.consultant",
                        verbose_name="Consultor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arquivo do consultor",
                "verbose_name_plural": "Arquivos do consultor",
            },
        ),
    ]
