# Generated by Django 5.2.6 on 2025-12-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0007_consultantattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="criticality",
            field=models.CharField(
                choices=[
                    ("low", "Baixa"),
                    ("medium", "Media"),
                    ("high", "Alta"),
                    ("critical", "Critico"),
                ],
                default="medium",
                max_length=20,
                verbose_name="Criticidade",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="explanation",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Explicacao do projeto",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[("billable", "Faturavel"), ("internal", "Projeto interno")],
                default="billable",
                max_length=20,
                verbose_name="Tipo de projeto",
            ),
        ),
    ]
