# Generated by Django 5.2.6 on 2025-12-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0008_project_explanation_project_type_criticality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deploymenttemplate",
            name="description",
            field=models.CharField(max_length=200, verbose_name="Nome do template"),
        ),
        migrations.RemoveField(
            model_name="deploymenttemplate",
            name="project",
        ),
    ]
