# Generated by Django 5.2.6 on 2025-12-24 18:02

import django.db.models.deletion
from django.db import migrations, models


def forwards_create_template_headers(apps, schema_editor):
    template_model = apps.get_model("cadastros", "DeploymentTemplateHeader")
    item_model = apps.get_model("cadastros", "DeploymentTemplate")
    db_alias = schema_editor.connection.alias
    headers = {}
    for item in item_model.objects.using(db_alias).all():
        name = (item.description or "").strip() or "Template sem nome"
        header = headers.get(name)
        if header is None:
            header = template_model.objects.using(db_alias).create(name=name)
            headers[name] = header
        item.template_id = header.id
        item.save(update_fields=["template"])


def backwards_restore_description(apps, schema_editor):
    template_model = apps.get_model("cadastros", "DeploymentTemplateHeader")
    item_model = apps.get_model("cadastros", "DeploymentTemplate")
    db_alias = schema_editor.connection.alias
    names = {
        template.id: template.name
        for template in template_model.objects.using(db_alias).all()
    }
    for item in item_model.objects.using(db_alias).all():
        item.description = names.get(item.template_id, "")
        item.save(update_fields=["description"])


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0009_remove_deploymenttemplate_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeploymentTemplateHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Nome do template"
                    ),
                ),
            ],
            options={
                "verbose_name": "Template de implantacao",
                "verbose_name_plural": "Templates de implantacao",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="deploymenttemplate",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="cadastros.deploymenttemplateheader",
                verbose_name="Template",
            ),
        ),
        migrations.RunPython(
            forwards_create_template_headers,
            backwards_restore_description,
        ),
        migrations.AlterField(
            model_name="deploymenttemplate",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="cadastros.deploymenttemplateheader",
                verbose_name="Template",
            ),
        ),
        migrations.RemoveField(
            model_name="deploymenttemplate",
            name="description",
        ),
        migrations.AlterModelOptions(
            name="deploymenttemplate",
            options={
                "ordering": ("template", "seq"),
                "verbose_name": "Item do template",
                "verbose_name_plural": "Itens do template",
            },
        ),
    ]
