# Generated by Django 5.2.6 on 2025-12-25 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0010_deploymenttemplate_header_items"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountPlanTemplateHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Nome do modelo"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descricao")),
            ],
            options={
                "verbose_name": "Modelo de plano de contas",
                "verbose_name_plural": "Modelos de plano de contas",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="AccountPlanTemplateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("code", models.CharField(max_length=40, verbose_name="Codigo")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Descricao"),
                ),
                ("level", models.PositiveSmallIntegerField(verbose_name="Nivel")),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "Ativo"),
                            ("liability", "Passivo"),
                            ("equity", "Patrimonio liquido"),
                            ("revenue", "Receita"),
                            ("cost", "Custo"),
                            ("expense", "Despesa"),
                            ("other", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de conta",
                    ),
                ),
                (
                    "nature",
                    models.CharField(
                        choices=[("debit", "Debito"), ("credit", "Credito")],
                        max_length=10,
                        verbose_name="Natureza",
                    ),
                ),
                (
                    "is_analytic",
                    models.BooleanField(default=True, verbose_name="Analitica"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("inactive", "Inativo"),
                            ("pending", "Pendente"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "dre_group",
                    models.CharField(max_length=120, verbose_name="Grupo DRE"),
                ),
                (
                    "dre_subgroup",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Linha DRE"
                    ),
                ),
                (
                    "dre_order",
                    models.PositiveSmallIntegerField(verbose_name="Ordem DRE"),
                ),
                (
                    "dre_sign",
                    models.CharField(
                        choices=[("add", "Somar"), ("subtract", "Subtrair")],
                        default="add",
                        max_length=10,
                        verbose_name="Sinal DRE",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="cadastros.accountplantemplateitem",
                        verbose_name="Conta pai",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cadastros.accountplantemplateheader",
                        verbose_name="Modelo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta do modelo",
                "verbose_name_plural": "Contas do modelo",
                "ordering": ("template", "code"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("template", "code"),
                        name="unique_account_code_per_template",
                    )
                ],
            },
        ),
    ]
