# Generated by Django 5.2.6 on 2025-12-25 13:18

from django.db import migrations


def seed_account_plan_template(apps, schema_editor):
    template_name = "Consultoria ERP - Plano de contas"
    template_description = "Modelo base para consultoria de implantacao de sistemas ERP."

    AccountPlanTemplateHeader = apps.get_model(
        "cadastros", "AccountPlanTemplateHeader"
    )
    AccountPlanTemplateItem = apps.get_model("cadastros", "AccountPlanTemplateItem")

    header = AccountPlanTemplateHeader.objects.filter(name=template_name).first()
    if header and AccountPlanTemplateItem.objects.filter(template=header).exists():
        return
    if header is None:
        header = AccountPlanTemplateHeader.objects.create(
            name=template_name,
            description=template_description,
        )

    items = []

    def add_item(
        code,
        description,
        level,
        parent_code,
        account_type,
        nature,
        is_analytic,
        dre_group,
        dre_order,
        dre_sign,
        dre_subgroup="",
    ):
        items.append(
            {
                "code": code,
                "description": description,
                "level": level,
                "parent_code": parent_code,
                "account_type": account_type,
                "nature": nature,
                "is_analytic": is_analytic,
                "status": "active",
                "dre_group": dre_group,
                "dre_subgroup": dre_subgroup,
                "dre_order": dre_order,
                "dre_sign": dre_sign,
            }
        )

    # Receita bruta
    add_item("1", "Receita de servicos", 1, None, "revenue", "credit", False, "Receita bruta", 10, "add")
    add_item("1.01", "Implantacao ERP", 2, "1", "revenue", "credit", False, "Receita bruta", 11, "add")
    add_item("1.01.01", "Consultoria funcional", 3, "1.01", "revenue", "credit", True, "Receita bruta", 12, "add", "Consultoria funcional")
    add_item("1.01.02", "Consultoria tecnica", 3, "1.01", "revenue", "credit", True, "Receita bruta", 13, "add", "Consultoria tecnica")
    add_item("1.01.03", "Parametrizacao", 3, "1.01", "revenue", "credit", True, "Receita bruta", 14, "add", "Parametrizacao")
    add_item("1.01.04", "Integracoes e customizacoes", 3, "1.01", "revenue", "credit", True, "Receita bruta", 15, "add", "Integracoes e customizacoes")
    add_item("1.01.05", "Gerenciamento de projeto", 3, "1.01", "revenue", "credit", True, "Receita bruta", 16, "add", "Gerenciamento de projeto")
    add_item("1.02", "Suporte e evolucao", 2, "1", "revenue", "credit", False, "Receita bruta", 17, "add")
    add_item("1.02.01", "Suporte mensal", 3, "1.02", "revenue", "credit", True, "Receita bruta", 18, "add", "Suporte mensal")
    add_item("1.02.02", "Sustentacao on-demand", 3, "1.02", "revenue", "credit", True, "Receita bruta", 19, "add", "Sustentacao on-demand")
    add_item("1.03", "Treinamento", 2, "1", "revenue", "credit", False, "Receita bruta", 20, "add")
    add_item("1.03.01", "Treinamento presencial", 3, "1.03", "revenue", "credit", True, "Receita bruta", 21, "add", "Treinamento presencial")
    add_item("1.03.02", "Treinamento remoto", 3, "1.03", "revenue", "credit", True, "Receita bruta", 22, "add", "Treinamento remoto")
    add_item("1.04", "Reembolso de despesas", 2, "1", "revenue", "credit", False, "Receita bruta", 23, "add")
    add_item("1.04.01", "Reembolso de viagens", 3, "1.04", "revenue", "credit", True, "Receita bruta", 24, "add", "Reembolso de viagens")
    add_item("1.04.02", "Reembolso de hospedagem", 3, "1.04", "revenue", "credit", True, "Receita bruta", 25, "add", "Reembolso de hospedagem")
    add_item("1.05", "Revenda de licencas", 2, "1", "revenue", "credit", False, "Receita bruta", 26, "add")
    add_item("1.05.01", "Repasse licencas ERP", 3, "1.05", "revenue", "credit", True, "Receita bruta", 27, "add", "Repasse licencas ERP")
    add_item("1.05.02", "Repasse licencas terceiros", 3, "1.05", "revenue", "credit", True, "Receita bruta", 28, "add", "Repasse licencas terceiros")

    # Deducoes da receita
    add_item("2", "Deducoes da receita", 1, None, "expense", "debit", False, "Deducoes da receita", 30, "subtract")
    add_item("2.01", "Impostos sobre faturamento", 2, "2", "expense", "debit", False, "Deducoes da receita", 31, "subtract")
    add_item("2.01.01", "ISS", 3, "2.01", "expense", "debit", True, "Deducoes da receita", 32, "subtract", "ISS")
    add_item("2.01.02", "PIS", 3, "2.01", "expense", "debit", True, "Deducoes da receita", 33, "subtract", "PIS")
    add_item("2.01.03", "COFINS", 3, "2.01", "expense", "debit", True, "Deducoes da receita", 34, "subtract", "COFINS")
    add_item("2.01.04", "IRRF retido", 3, "2.01", "expense", "debit", True, "Deducoes da receita", 35, "subtract", "IRRF retido")
    add_item("2.01.05", "CSLL retida", 3, "2.01", "expense", "debit", True, "Deducoes da receita", 36, "subtract", "CSLL retida")
    add_item("2.02", "Descontos concedidos", 2, "2", "expense", "debit", False, "Deducoes da receita", 37, "subtract")
    add_item("2.02.01", "Descontos comerciais", 3, "2.02", "expense", "debit", True, "Deducoes da receita", 38, "subtract", "Descontos comerciais")

    # Custos dos servicos
    add_item("3", "Custos dos servicos", 1, None, "cost", "debit", False, "Custos dos servicos", 40, "subtract")
    add_item("3.01", "Custos com equipe", 2, "3", "cost", "debit", False, "Custos dos servicos", 41, "subtract")
    add_item("3.01.01", "Salarios consultores", 3, "3.01", "cost", "debit", True, "Custos dos servicos", 42, "subtract", "Salarios consultores")
    add_item("3.01.02", "Encargos e beneficios", 3, "3.01", "cost", "debit", True, "Custos dos servicos", 43, "subtract", "Encargos e beneficios")
    add_item("3.01.03", "Bonus produtividade", 3, "3.01", "cost", "debit", True, "Custos dos servicos", 44, "subtract", "Bonus produtividade")
    add_item("3.02", "Custos com terceiros", 2, "3", "cost", "debit", False, "Custos dos servicos", 45, "subtract")
    add_item("3.02.01", "Subcontratados", 3, "3.02", "cost", "debit", True, "Custos dos servicos", 46, "subtract", "Subcontratados")
    add_item("3.02.02", "Freelancers especialistas", 3, "3.02", "cost", "debit", True, "Custos dos servicos", 47, "subtract", "Freelancers especialistas")
    add_item("3.03", "Custos com viagens projeto", 2, "3", "cost", "debit", False, "Custos dos servicos", 48, "subtract")
    add_item("3.03.01", "Passagens", 3, "3.03", "cost", "debit", True, "Custos dos servicos", 49, "subtract", "Passagens")
    add_item("3.03.02", "Hospedagem", 3, "3.03", "cost", "debit", True, "Custos dos servicos", 50, "subtract", "Hospedagem")
    add_item("3.03.03", "Alimentacao", 3, "3.03", "cost", "debit", True, "Custos dos servicos", 51, "subtract", "Alimentacao")
    add_item("3.04", "Custos com infraestrutura", 2, "3", "cost", "debit", False, "Custos dos servicos", 52, "subtract")
    add_item("3.04.01", "Licencas de ferramentas", 3, "3.04", "cost", "debit", True, "Custos dos servicos", 53, "subtract", "Licencas de ferramentas")
    add_item("3.04.02", "Cloud e hospedagem", 3, "3.04", "cost", "debit", True, "Custos dos servicos", 54, "subtract", "Cloud e hospedagem")

    # Despesas operacionais
    add_item("4", "Despesas operacionais", 1, None, "expense", "debit", False, "Despesas operacionais", 60, "subtract")
    add_item("4.01", "Despesas administrativas", 2, "4", "expense", "debit", False, "Despesas operacionais", 61, "subtract")
    add_item("4.01.01", "Aluguel", 3, "4.01", "expense", "debit", True, "Despesas operacionais", 62, "subtract", "Aluguel")
    add_item("4.01.02", "Energia e agua", 3, "4.01", "expense", "debit", True, "Despesas operacionais", 63, "subtract", "Energia e agua")
    add_item("4.01.03", "Telefonia e internet", 3, "4.01", "expense", "debit", True, "Despesas operacionais", 64, "subtract", "Telefonia e internet")
    add_item("4.01.04", "Contabilidade e juridico", 3, "4.01", "expense", "debit", True, "Despesas operacionais", 65, "subtract", "Contabilidade e juridico")
    add_item("4.02", "Despesas comerciais", 2, "4", "expense", "debit", False, "Despesas operacionais", 66, "subtract")
    add_item("4.02.01", "Marketing e eventos", 3, "4.02", "expense", "debit", True, "Despesas operacionais", 67, "subtract", "Marketing e eventos")
    add_item("4.02.02", "Propostas e pre-vendas", 3, "4.02", "expense", "debit", True, "Despesas operacionais", 68, "subtract", "Propostas e pre-vendas")
    add_item("4.02.03", "Comissoes", 3, "4.02", "expense", "debit", True, "Despesas operacionais", 69, "subtract", "Comissoes")
    add_item("4.03", "Despesas gerais", 2, "4", "expense", "debit", False, "Despesas operacionais", 70, "subtract")
    add_item("4.03.01", "Taxas bancarias", 3, "4.03", "expense", "debit", True, "Despesas operacionais", 71, "subtract", "Taxas bancarias")
    add_item("4.03.02", "Seguros", 3, "4.03", "expense", "debit", True, "Despesas operacionais", 72, "subtract", "Seguros")
    add_item("4.03.03", "Servicos terceirizados", 3, "4.03", "expense", "debit", True, "Despesas operacionais", 73, "subtract", "Servicos terceirizados")

    # Outras receitas/despesas
    add_item("5", "Outras receitas e despesas", 1, None, "other", "credit", False, "Outras receitas/despesas", 80, "add")
    add_item("5.01", "Outras receitas", 2, "5", "revenue", "credit", False, "Outras receitas/despesas", 81, "add")
    add_item("5.01.01", "Juros ativos", 3, "5.01", "revenue", "credit", True, "Outras receitas/despesas", 82, "add", "Juros ativos")
    add_item("5.01.02", "Variacao cambial ativa", 3, "5.01", "revenue", "credit", True, "Outras receitas/despesas", 83, "add", "Variacao cambial ativa")
    add_item("5.02", "Outras despesas", 2, "5", "expense", "debit", False, "Outras receitas/despesas", 84, "subtract")
    add_item("5.02.01", "Juros passivos", 3, "5.02", "expense", "debit", True, "Outras receitas/despesas", 85, "subtract", "Juros passivos")
    add_item("5.02.02", "Variacao cambial passiva", 3, "5.02", "expense", "debit", True, "Outras receitas/despesas", 86, "subtract", "Variacao cambial passiva")
    add_item("5.02.03", "Multas e penalidades", 3, "5.02", "expense", "debit", True, "Outras receitas/despesas", 87, "subtract", "Multas e penalidades")

    code_map = {}
    for item in items:
        parent_code = item.pop("parent_code")
        parent = None
        if parent_code:
            parent = code_map.get(parent_code)
            if parent is None:
                raise ValueError(f"Conta pai nao encontrada: {parent_code}")
        record = AccountPlanTemplateItem.objects.create(
            template=header,
            parent=parent,
            **item,
        )
        code_map[record.code] = record


def remove_account_plan_template(apps, schema_editor):
    template_name = "Consultoria ERP - Plano de contas"
    AccountPlanTemplateHeader = apps.get_model(
        "cadastros", "AccountPlanTemplateHeader"
    )
    AccountPlanTemplateItem = apps.get_model("cadastros", "AccountPlanTemplateItem")

    header = AccountPlanTemplateHeader.objects.filter(name=template_name).first()
    if header is None:
        return
    AccountPlanTemplateItem.objects.filter(template=header).delete()
    header.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0011_accountplantemplateheader_accountplantemplateitem"),
    ]

    operations = [
        migrations.RunPython(seed_account_plan_template, remove_account_plan_template),
    ]
