# Generated by Django 5.2.6 on 2025-12-25 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_user_profiles(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)
    UserProfile = apps.get_model("cadastros", "UserProfile")

    for user in User.objects.all():
        if UserProfile.objects.filter(user_id=user.id).exists():
            continue
        role = "admin" if user.is_superuser or user.is_staff else "consultant"
        UserProfile.objects.create(user_id=user.id, role=role)


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0012_seed_account_plan_template"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consultant",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consultant_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario vinculado",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("gp_internal", "GP interno"),
                            ("gp_external", "GP externo"),
                            ("consultant", "Consultor"),
                            ("client", "Cliente"),
                        ],
                        default="consultant",
                        max_length=20,
                        verbose_name="Perfil",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de usuario",
                "verbose_name_plural": "Perfis de usuario",
            },
        ),
        migrations.RunPython(create_user_profiles, migrations.RunPython.noop),
        migrations.CreateModel(
            name="ProjectActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("seq", models.PositiveSmallIntegerField(verbose_name="Seq")),
                (
                    "seq_predecessor",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Seq predecessora"
                    ),
                ),
                (
                    "activity",
                    models.CharField(max_length=200, verbose_name="Atividade"),
                ),
                (
                    "subactivity",
                    models.CharField(max_length=200, verbose_name="Subatividade"),
                ),
                ("days", models.PositiveSmallIntegerField(verbose_name="Dias")),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Horas"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planejada"),
                            ("in_progress", "Em andamento"),
                            ("done", "Concluida"),
                            ("blocked", "Bloqueada"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "client_visible",
                    models.BooleanField(
                        default=False, verbose_name="Visivel ao cliente"
                    ),
                ),
                (
                    "client_completed",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Concluida pelo cliente"
                    ),
                ),
                (
                    "client_comment",
                    models.TextField(blank=True, verbose_name="Comentario do cliente"),
                ),
                (
                    "client_feedback_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Feedback em"
                    ),
                ),
                (
                    "client_feedback_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_activity_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Feedback por",
                    ),
                ),
                (
                    "consultants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="project_activities",
                        to="cadastros.consultant",
                        verbose_name="Consultores",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_activities",
                        to="cadastros.module",
                        verbose_name="Modulo",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_activities",
                        to="cadastros.phase",
                        verbose_name="Fase",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_activities",
                        to="cadastros.product",
                        verbose_name="Produto",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="cadastros.project",
                        verbose_name="Projeto",
                    ),
                ),
                (
                    "submodule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_activities",
                        to="cadastros.submodule",
                        verbose_name="Submodulo",
                    ),
                ),
                (
                    "template_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_activities",
                        to="cadastros.deploymenttemplate",
                        verbose_name="Item do template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atividade do projeto",
                "verbose_name_plural": "Atividades do projeto",
                "ordering": ("project", "seq"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "seq"), name="unique_project_activity_seq"
                    )
                ],
            },
        ),
    ]
