# Generated by Django 5.2.6 on 2025-12-25 20:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0013_consultant_user_userprofile_projectactivity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectactivity",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "Pendente"),
                    ("planned", "Planejada"),
                    ("released", "Liberada"),
                    ("done", "Concluida"),
                    ("blocked", "Paralizada"),
                    ("canceled", "Cancelada"),
                ],
                default="planned",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("daily", "Diario"), ("weekly", "Semanal")],
                        default="daily",
                        max_length=10,
                        verbose_name="Tipo de apontamento",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("approved", "Aprovada"),
                            ("rejected", "Reprovada"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Data inicial")),
                ("end_date", models.DateField(verbose_name="Data final")),
                (
                    "hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Horas (total)",
                    ),
                ),
                (
                    "hours_monday",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Horas segunda",
                    ),
                ),
                (
                    "hours_tuesday",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Horas terca",
                    ),
                ),
                (
                    "hours_wednesday",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Horas quarta",
                    ),
                ),
                (
                    "hours_thursday",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Horas quinta",
                    ),
                ),
                (
                    "hours_friday",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Horas sexta",
                    ),
                ),
                (
                    "hours_saturday",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Horas sabado",
                    ),
                ),
                (
                    "hours_sunday",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Horas domingo",
                    ),
                ),
                (
                    "total_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        verbose_name="Horas totais",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descricao do servico"),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Motivo da reprovacao"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Revisado em"
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to="cadastros.projectactivity",
                        verbose_name="Atividade",
                    ),
                ),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="time_entries",
                        to="cadastros.consultant",
                        verbose_name="Consultor",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="time_entries_reviewed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Revisado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apontamento",
                "verbose_name_plural": "Apontamentos",
                "ordering": ("-created_at",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))),
                        name="time_entry_end_date_gte_start_date",
                    )
                ],
            },
        ),
    ]
