# Generated by Django 5.2.6 on 2025-12-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0014_alter_projectactivity_status_timeentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectactivity",
            name="actual_end",
            field=models.DateField(blank=True, null=True, verbose_name="Fim real"),
        ),
        migrations.AddField(
            model_name="projectactivity",
            name="actual_start",
            field=models.DateField(blank=True, null=True, verbose_name="Inicio real"),
        ),
        migrations.AddField(
            model_name="projectactivity",
            name="planned_end",
            field=models.DateField(blank=True, null=True, verbose_name="Fim previsto"),
        ),
        migrations.AddField(
            model_name="projectactivity",
            name="planned_start",
            field=models.DateField(
                blank=True, null=True, verbose_name="Inicio previsto"
            ),
        ),
    ]
