# Generated by Django 5.2.6 on 2025-12-25 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0015_projectactivity_actual_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectactivity",
            name="account_plan_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_activities",
                to="cadastros.accountplantemplateitem",
                verbose_name="Conta do plano de contas",
            ),
        ),
    ]
