# Generated by Django 5.2.6 on 2025-12-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0016_projectactivity_account_plan_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultant",
            name="is_partner",
            field=models.BooleanField(default=False, verbose_name="Socio"),
        ),
        migrations.AddField(
            model_name="consultant",
            name="is_senior_accredited",
            field=models.BooleanField(default=False, verbose_name="Credenciado senior"),
        ),
    ]
