# Generated by Django 5.2.6 on 2025-12-26 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0017_consultant_is_partner_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultantBankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("pf", "Pessoa fisica"), ("pj", "Pessoa juridica")],
                        default="pf",
                        max_length=2,
                        verbose_name="Tipo de conta",
                    ),
                ),
                ("bank_name", models.CharField(max_length=120, verbose_name="Banco")),
                ("agency", models.CharField(max_length=20, verbose_name="Agencia")),
                (
                    "account_number",
                    models.CharField(max_length=30, verbose_name="Conta"),
                ),
                (
                    "account_digit",
                    models.CharField(blank=True, max_length=10, verbose_name="Digito"),
                ),
                ("pix_keys", models.TextField(blank=True, verbose_name="Chaves Pix")),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="cadastros.consultant",
                        verbose_name="Consultor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta bancaria do consultor",
                "verbose_name_plural": "Contas bancarias do consultor",
            },
        ),
    ]
