# Generated by Django 5.2.6 on 2025-12-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0018_consultantbankaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectactivity",
            name="consultant_hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Valor hora consultor (R$)",
            ),
        ),
    ]
