# Generated by Django 5.2.6 on 2025-12-27 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0019_projectactivity_consultant_hourly_rate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="received_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de recebimento"
            ),
        ),
        migrations.CreateModel(
            name="ProjectObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "observation_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("auto", "Automatica"),
                            ("change", "Alteracao"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Observacao")),
                (
                    "changes",
                    models.JSONField(blank=True, null=True, verbose_name="Alteracoes"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_observations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="cadastros.project",
                        verbose_name="Projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Observacao do projeto",
                "verbose_name_plural": "Observacoes do projeto",
                "ordering": ("-created_at",),
            },
        ),
    ]
