# Generated by Django 5.2.6 on 2025-12-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0020_project_received_date_projectobservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectactivity",
            name="billing_type",
            field=models.CharField(
                choices=[
                    ("billable", "Faturavel"),
                    ("assumed_rework", "Horas assumidas - Retrabalho"),
                    ("assumed_unplanned", "Horas assumidas - Nao planejadas"),
                    ("assumed_courtesy", "Horas assumidas - Cortezia"),
                ],
                default="billable",
                max_length=20,
                verbose_name="Classificacao de horas",
            ),
        ),
    ]
