# Generated by Django 5.2.6 on 2025-12-28 00:19

import cadastros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0021_projectactivity_billing_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="Nome completo"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Telefone"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Cidade/Estado"
                    ),
                ),
                (
                    "role_interest",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Area de interesse"
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True, verbose_name="Linkedin")),
                (
                    "availability",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Disponibilidade"
                    ),
                ),
                (
                    "experience_summary",
                    models.TextField(blank=True, verbose_name="Resumo profissional"),
                ),
                (
                    "resume",
                    models.FileField(
                        upload_to=cadastros.models._candidate_resume_path,
                        verbose_name="Curriculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidatura",
                "verbose_name_plural": "Candidaturas",
            },
        ),
        migrations.CreateModel(
            name="ProposalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=200, verbose_name="Empresa"),
                ),
                (
                    "contact_name",
                    models.CharField(max_length=150, verbose_name="Contato"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Telefone"
                    ),
                ),
                ("project_summary", models.TextField(verbose_name="Resumo do projeto")),
                (
                    "estimated_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Inicio desejado"
                    ),
                ),
                (
                    "budget_range",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Faixa de investimento"
                    ),
                ),
                (
                    "additional_notes",
                    models.TextField(blank=True, verbose_name="Observacoes"),
                ),
            ],
            options={
                "verbose_name": "Solicitacao de proposta",
                "verbose_name_plural": "Solicitacoes de proposta",
            },
        ),
    ]
