# Generated by Django 5.2.6 on 2025-12-29 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0023_project_planned_go_live_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="Papel"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("inactive", "Inativo"),
                            ("pending", "Pendente"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Situacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Papel de projeto",
                "verbose_name_plural": "Papeis de projeto",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ProjectContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nome")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Telefone"
                    ),
                ),
                (
                    "function",
                    models.CharField(blank=True, max_length=120, verbose_name="Funcao"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "receives_status_report",
                    models.BooleanField(
                        default=False, verbose_name="Recebe status report"
                    ),
                ),
                (
                    "receives_delay_email",
                    models.BooleanField(
                        default=False, verbose_name="Recebe e-mail de atrasos"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="cadastros.project",
                        verbose_name="Projeto",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_contacts",
                        to="cadastros.projectrole",
                        verbose_name="Papel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pessoa do projeto",
                "verbose_name_plural": "Pessoas do projeto",
                "ordering": ("project", "name"),
            },
        ),
    ]
