# Generated by Django 5.2.6 on 2025-12-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0024_projectrole_projectcontact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectcontact",
            name="receives_delay_email",
            field=models.BooleanField(default=False, verbose_name="Rec e-mail atrasos"),
        ),
        migrations.AlterField(
            model_name="projectcontact",
            name="receives_status_report",
            field=models.BooleanField(default=False, verbose_name="Rec status report"),
        ),
    ]
