# Generated by Django 5.2.6 on 2025-12-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0025_alter_projectcontact_receives_delay_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectactivity",
            name="criticality",
            field=models.CharField(
                choices=[
                    ("low", "Baixa"),
                    ("medium", "Media"),
                    ("high", "Alta"),
                    ("critical", "Critica"),
                ],
                default="medium",
                max_length=20,
                verbose_name="Criticidade",
            ),
        ),
        migrations.AddField(
            model_name="projectactivity",
            name="predecessors",
            field=models.ManyToManyField(
                blank=True,
                related_name="successors",
                to="cadastros.projectactivity",
                verbose_name="Predecessoras",
            ),
        ),
        migrations.AlterField(
            model_name="projectactivity",
            name="days",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="Dias"
            ),
        ),
    ]
