# Generated by Codex on 2025-12-29

from django.db import migrations


def forwards(apps, schema_editor):
    ProjectActivity = apps.get_model("cadastros", "ProjectActivity")
    for activity in ProjectActivity.objects.exclude(seq_predecessor__isnull=True):
        predecessor = ProjectActivity.objects.filter(
            project_id=activity.project_id,
            seq=activity.seq_predecessor,
        ).first()
        if predecessor:
            activity.predecessors.add(predecessor)


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0026_projectactivity_criticality_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
