# Generated by Django 5.2.6 on 2025-12-29 16:51

import django.db.models.deletion
from django.db import migrations, models


def backfill_projectactivity_subactivities(apps, schema_editor):
    ProjectActivity = apps.get_model("cadastros", "ProjectActivity")
    ProjectActivitySubactivity = apps.get_model("cadastros", "ProjectActivitySubactivity")
    db_alias = schema_editor.connection.alias
    existing = set(
        ProjectActivitySubactivity.objects.using(db_alias).values_list(
            "activity_id", flat=True
        )
    )
    records = []
    for activity in ProjectActivity.objects.using(db_alias).iterator():
        if activity.id in existing:
            continue
        text = (activity.subactivity or "").strip()
        if not text:
            continue
        records.append(
            ProjectActivitySubactivity(
                activity_id=activity.id,
                description=text,
                order=1,
            )
        )
    if records:
        ProjectActivitySubactivity.objects.using(db_alias).bulk_create(records)


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0027_backfill_projectactivity_predecessors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectactivity",
            name="subactivity",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Subatividade"
            ),
        ),
        migrations.CreateModel(
            name="ProjectActivitySubactivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Subatividade"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Ordem"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subactivity_items",
                        to="cadastros.projectactivity",
                        verbose_name="Atividade do projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subatividade do projeto",
                "verbose_name_plural": "Subatividades do projeto",
                "ordering": ("activity", "order", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("activity", "order"),
                        name="unique_project_activity_subactivity_order",
                    )
                ],
            },
        ),
        migrations.RunPython(
            backfill_projectactivity_subactivities, migrations.RunPython.noop
        ),
    ]
