# Generated by Django 5.2.6 on 2025-12-29 18:24

import cadastros.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0028_alter_projectactivity_subactivity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeEntryAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=cadastros.models._time_entry_attachment_path,
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "time_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="cadastros.timeentry",
                        verbose_name="Apontamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anexo do apontamento",
                "verbose_name_plural": "Anexos do apontamento",
                "ordering": ("-created_at",),
            },
        ),
    ]
