# Generated by Django 5.2.6 on 2025-12-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0029_timeentryattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="cloud_environment",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Ambiente cloud do cliente",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="database_type",
            field=models.CharField(
                blank=True,
                choices=[("sql_server", "SQL Server"), ("oracle", "Oracle")],
                default="",
                max_length=20,
                verbose_name="Banco de dados",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="hml_url",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Endereco HML"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="prd_url",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Endereco PRD"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="senior_client_code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=60,
                verbose_name="Codigo do cliente na Senior",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="senior_project_code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=60,
                verbose_name="Codigo do projeto na Senior",
            ),
        ),
    ]
