# Generated by Django 5.2.6 on 2025-12-30 17:07

import cadastros.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0030_project_cloud_environment_project_database_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titulo")),
                ("description", models.TextField(blank=True, verbose_name="Descricao")),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Aberto"), ("closed", "Encerrado")],
                        default="open",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Encerrado em"
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="cadastros.projectactivity",
                        verbose_name="Atividade",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets_assigned",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Direcionado para",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets_closed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Encerrado por",
                    ),
                ),
                (
                    "consultant_responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets_responsible",
                        to="cadastros.consultant",
                        verbose_name="Consultor responsavel",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="cadastros.project",
                        verbose_name="Projeto",
                    ),
                ),
                (
                    "project_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="cadastros.projectrole",
                        verbose_name="Papel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chamado",
                "verbose_name_plural": "Chamados",
                "ordering": ("-updated_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="TicketAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=cadastros.models._ticket_attachment_path,
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="cadastros.ticket",
                        verbose_name="Chamado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anexo do chamado",
                "verbose_name_plural": "Anexos do chamado",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TicketReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("message", models.TextField(verbose_name="Mensagem")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ticket_replies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="cadastros.ticket",
                        verbose_name="Chamado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resposta do chamado",
                "verbose_name_plural": "Respostas do chamado",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="TicketReplyAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=cadastros.models._ticket_reply_attachment_path,
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "reply",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="cadastros.ticketreply",
                        verbose_name="Resposta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anexo da resposta",
                "verbose_name_plural": "Anexos da resposta",
                "ordering": ("-created_at",),
            },
        ),
    ]
