# Generated by Django 5.2.6 on 2025-12-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0031_ticket_ticketattachment_ticketreply_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultant",
            name="birth_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de nascimento"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="criticality",
            field=models.CharField(
                choices=[
                    ("low", "Baixa"),
                    ("medium", "Media"),
                    ("high", "Alta"),
                    ("critical", "Critica"),
                ],
                default="medium",
                max_length=20,
                verbose_name="Criticidade",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="ticket_type",
            field=models.CharField(
                choices=[
                    ("question", "Duvida"),
                    ("error", "Erro"),
                    ("improvement", "Solicitacao de melhoria"),
                ],
                default="question",
                max_length=20,
                verbose_name="Tipo de chamado",
            ),
        ),
    ]
