# Generated by Django 5.2.6 on 2025-12-31 00:00

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0032_consultant_birth_date_ticket_criticality_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="Numero da fatura"
                    ),
                ),
                (
                    "period_start",
                    models.DateField(verbose_name="Periodo inicial"),
                ),
                (
                    "period_end",
                    models.DateField(verbose_name="Periodo final"),
                ),
                (
                    "total_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Horas totais",
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Valor total (R$)",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("unpaid", "Nao pago"), ("paid", "Pago")],
                        default="unpaid",
                        max_length=10,
                        verbose_name="Status de pagamento",
                    ),
                ),
                (
                    "billing_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billing_invoices",
                        to="cadastros.client",
                        verbose_name="Cliente de faturamento",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_invoices_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billing_invoices",
                        to="cadastros.project",
                        verbose_name="Projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fatura",
                "verbose_name_plural": "Faturas",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="BillingInvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        verbose_name="Horas",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Tarifa",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total",
                    ),
                ),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billing_items",
                        to="cadastros.consultant",
                        verbose_name="Consultor",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cadastros.billinginvoice",
                        verbose_name="Fatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de fatura",
                "verbose_name_plural": "Itens de fatura",
                "ordering": ("consultant", "id"),
            },
        ),
        migrations.AddField(
            model_name="timeentry",
            name="billing_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_entries",
                to="cadastros.billinginvoice",
                verbose_name="Fatura",
            ),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="billing_invoice_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=40,
                verbose_name="Numero da fatura",
            ),
        ),
    ]
