# Generated by Django 5.2.6 on 2025-12-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0033_billing_invoice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "person_type",
                    models.CharField(
                        choices=[("pf", "Pessoa fisica"), ("pj", "Pessoa juridica")],
                        default="pj",
                        max_length=2,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "document",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="CPF/CNPJ"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nome/Razao social"),
                ),
                (
                    "trade_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nome fantasia"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Telefone"
                    ),
                ),
                (
                    "address_line",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Endereco"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
                ),
                (
                    "state",
                    models.CharField(blank=True, max_length=100, verbose_name="Estado"),
                ),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=20, verbose_name="CEP"),
                ),
                (
                    "country",
                    models.CharField(default="BR", max_length=2, verbose_name="Pais"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("inactive", "Inativo"),
                            ("pending", "Pendente"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observacoes")),
            ],
            options={
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedores",
            },
        ),
    ]
