# Generated by Django 5.2.6 on 2025-12-31 01:43

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0034_supplier"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountsPayable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "document_number",
                    models.CharField(max_length=60, verbose_name="Numero do documento"),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Descricao"),
                ),
                (
                    "issue_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Data de emissao",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Data de vencimento")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Desconto",
                    ),
                ),
                (
                    "interest",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Juros",
                    ),
                ),
                (
                    "penalty",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Multa",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Aberto"),
                            ("overdue", "Atrasado"),
                            ("paid", "Pago"),
                            ("canceled", "Cancelado"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "settlement_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de liquidacao"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pix", "Pix"),
                            ("transfer", "Transferencia"),
                            ("boleto", "Boleto"),
                            ("card", "Cartao"),
                            ("cash", "Dinheiro"),
                            ("other", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Forma de pagamento",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observacoes")),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts_payable",
                        to="cadastros.supplier",
                        verbose_name="Fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta a pagar",
                "verbose_name_plural": "Contas a pagar",
                "ordering": ("due_date", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("supplier", "document_number"),
                        name="unique_payable_document_per_supplier",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AccountsReceivable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "document_number",
                    models.CharField(max_length=60, verbose_name="Numero do documento"),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Descricao"),
                ),
                (
                    "issue_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Data de emissao",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Data de vencimento")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Desconto",
                    ),
                ),
                (
                    "interest",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Juros",
                    ),
                ),
                (
                    "penalty",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Multa",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Aberto"),
                            ("overdue", "Atrasado"),
                            ("paid", "Pago"),
                            ("canceled", "Cancelado"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "settlement_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de liquidacao"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pix", "Pix"),
                            ("transfer", "Transferencia"),
                            ("boleto", "Boleto"),
                            ("card", "Cartao"),
                            ("cash", "Dinheiro"),
                            ("other", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Forma de pagamento",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observacoes")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts_receivable",
                        to="cadastros.client",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta a receber",
                "verbose_name_plural": "Contas a receber",
                "ordering": ("due_date", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("client", "document_number"),
                        name="unique_receivable_document_per_client",
                    )
                ],
            },
        ),
    ]
