# Generated by Django 5.2.6 on 2025-12-31 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0035_accountspayable_accountsreceivable"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultant",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consultants",
                to="cadastros.supplier",
                verbose_name="Fornecedor",
            ),
        ),
    ]
