# Generated by Django 5.2.6 on 2025-12-31 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0036_consultant_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountspayable",
            name="billing_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts_payable_titles",
                to="cadastros.billinginvoice",
                verbose_name="Fatura",
            ),
        ),
        migrations.AddField(
            model_name="accountspayable",
            name="consultant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounts_payable_titles",
                to="cadastros.consultant",
                verbose_name="Consultor",
            ),
        ),
        migrations.AddField(
            model_name="accountsreceivable",
            name="billing_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts_receivable_titles",
                to="cadastros.billinginvoice",
                verbose_name="Fatura",
            ),
        ),
    ]
