# Generated by Django 5.2.6 on 2025-12-31 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0037_accountspayable_billing_invoice_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyBankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("pf", "Pessoa fisica"), ("pj", "Pessoa juridica")],
                        default="pj",
                        max_length=2,
                        verbose_name="Tipo de conta",
                    ),
                ),
                ("bank_name", models.CharField(max_length=120, verbose_name="Banco")),
                ("agency", models.CharField(max_length=20, verbose_name="Agencia")),
                (
                    "account_number",
                    models.CharField(max_length=30, verbose_name="Conta"),
                ),
                (
                    "account_digit",
                    models.CharField(blank=True, max_length=10, verbose_name="Digito"),
                ),
                ("pix_keys", models.TextField(blank=True, verbose_name="Chaves Pix")),
                (
                    "company",
                    models.ForeignKey(
                        limit_choices_to={"company_type__in": ["primary", "branch"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="cadastros.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta bancaria da consultoria",
                "verbose_name_plural": "Contas bancarias da consultoria",
            },
        ),
    ]
