# Generated by Django 5.2.6 on 2025-12-31 02:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0038_companybankaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="companybankaccount",
            name="initial_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Saldo inicial",
            ),
        ),
    ]
