# Generated by Django 5.2.6 on 2025-12-31 03:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0039_companybankaccount_initial_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountsPayablePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "payment_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Data de pagamento",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor pago"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pix", "Pix"),
                            ("transfer", "Transferencia"),
                            ("boleto", "Boleto"),
                            ("card", "Cartao"),
                            ("cash", "Dinheiro"),
                            ("other", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Forma de pagamento",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observacoes")),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payable_payments",
                        to="cadastros.companybankaccount",
                        verbose_name="Conta bancaria",
                    ),
                ),
                (
                    "payable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="cadastros.accountspayable",
                        verbose_name="Conta a pagar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Baixa conta a pagar",
                "verbose_name_plural": "Baixas contas a pagar",
                "ordering": ("-payment_date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="AccountsReceivablePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "payment_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Data de recebimento",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor recebido"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pix", "Pix"),
                            ("transfer", "Transferencia"),
                            ("boleto", "Boleto"),
                            ("card", "Cartao"),
                            ("cash", "Dinheiro"),
                            ("other", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Forma de recebimento",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observacoes")),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receivable_payments",
                        to="cadastros.companybankaccount",
                        verbose_name="Conta bancaria",
                    ),
                ),
                (
                    "receivable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="cadastros.accountsreceivable",
                        verbose_name="Conta a receber",
                    ),
                ),
            ],
            options={
                "verbose_name": "Baixa conta a receber",
                "verbose_name_plural": "Baixas contas a receber",
                "ordering": ("-payment_date", "-created_at"),
            },
        ),
    ]
