# Generated by Django 5.2.6 on 2026-01-02 12:20

import cadastros.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0040_accountspayablepayment_accountsreceivablepayment"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountsPayableAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Descricao"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=cadastros.models._accounts_payable_attachment_path,
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "payable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="cadastros.accountspayable",
                        verbose_name="Conta a pagar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anexo da conta a pagar",
                "verbose_name_plural": "Anexos das contas a pagar",
                "ordering": ("-created_at",),
            },
        ),
    ]
