# Generated by Django 5.2.6 on 2026-01-03 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0041_accountspayableattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountspayable",
            name="account_plan_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts_payable_entries",
                to="cadastros.accountplantemplateitem",
                verbose_name="Conta do plano de contas",
            ),
        ),
        migrations.AddField(
            model_name="accountsreceivable",
            name="account_plan_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts_receivable_entries",
                to="cadastros.accountplantemplateitem",
                verbose_name="Conta do plano de contas",
            ),
        ),
    ]
