# Generated by Django 5.2.6 on 2026-01-03 11:00

from django.db import migrations
from django.db.models import Q


def update_title_account_plan_items(apps, schema_editor):
    AccountPlanTemplateItem = apps.get_model("cadastros", "AccountPlanTemplateItem")
    AccountsPayable = apps.get_model("cadastros", "AccountsPayable")
    AccountsReceivable = apps.get_model("cadastros", "AccountsReceivable")
    Supplier = apps.get_model("cadastros", "Supplier")

    def resolve_plan_item(code: str):
        return AccountPlanTemplateItem.objects.filter(code=code).order_by("id").first()

    receivable_item = resolve_plan_item("1.01.01")
    payable_item = resolve_plan_item("3.01.01")
    xisto_item = resolve_plan_item("4.01.04")

    if receivable_item:
        AccountsReceivable.objects.filter(
            billing_invoice__isnull=False,
            description__istartswith="TITULO GERADO PELA FATURA",
        ).update(account_plan_item=receivable_item)

    if payable_item:
        AccountsPayable.objects.filter(
            billing_invoice__isnull=False,
            description__istartswith="TITULO GERADO PELA FATURA",
        ).update(account_plan_item=payable_item)

    if xisto_item:
        xisto_suppliers = Supplier.objects.filter(
            Q(name__iexact="XISTO") | Q(trade_name__iexact="XISTO")
        )
        if xisto_suppliers.exists():
            AccountsPayable.objects.filter(
                supplier__in=xisto_suppliers
            ).update(account_plan_item=xisto_item)


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0042_account_plan_item_titles"),
    ]

    operations = [
        migrations.RunPython(
            update_title_account_plan_items,
            migrations.RunPython.noop,
        ),
    ]
