# Generated by Django 5.2.6 on 2026-01-03 17:20

from django.db import migrations
from django.db.models import Q


def update_xisto_titles(apps, schema_editor):
    AccountPlanTemplateItem = apps.get_model("cadastros", "AccountPlanTemplateItem")
    AccountsPayable = apps.get_model("cadastros", "AccountsPayable")
    Supplier = apps.get_model("cadastros", "Supplier")

    plan_item = (
        AccountPlanTemplateItem.objects.filter(code="4.01.04")
        .order_by("id")
        .first()
    )
    if not plan_item:
        return

    suppliers = Supplier.objects.filter(
        Q(name__iexact="DOUGLAS SANTIAGO XISTO")
        | Q(trade_name__iexact="DOUGLAS SANTIAGO XISTO")
    )
    if not suppliers.exists():
        return

    AccountsPayable.objects.filter(supplier__in=suppliers).update(
        account_plan_item=plan_item
    )


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0043_update_title_account_plan_item"),
    ]

    operations = [
        migrations.RunPython(update_xisto_titles, migrations.RunPython.noop),
    ]
