# Generated by Django 5.2.6 on 2026-01-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0044_update_title_account_plan_item_xisto_fullname"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="contract_type",
            field=models.CharField(
                choices=[
                    ("fixed_hours", "Pacote fechado por hora"),
                    ("fixed_value", "Pacote fechado por valor"),
                    ("hourly_project", "Projeto por horas"),
                    ("ad_hoc", "Demanda avulsa"),
                ],
                default="fixed_value",
                max_length=20,
                verbose_name="Classificacao do projeto",
            ),
        ),
    ]
