# Generated by Django 5.2.6 on 2026-01-15 10:35

import cadastros.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0051_knowledge_base"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="cutover_planned_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fim planejado do cutover"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="cutover_planned_start",
            field=models.DateField(
                blank=True, null=True, verbose_name="Inicio planejado do cutover"
            ),
        ),
        migrations.CreateModel(
            name="ProjectGoNoGoChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "criterion",
                    models.CharField(max_length=255, verbose_name="Criterio"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="Categoria"
                    ),
                ),
                (
                    "required_evidence",
                    models.TextField(
                        blank=True, verbose_name="Evidencias obrigatorias"
                    ),
                ),
                (
                    "approver",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="Aprovador"
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("ok", "OK"), ("no", "Nao"), ("pending", "Pendente")],
                        default="pending",
                        max_length=10,
                        verbose_name="Resultado",
                    ),
                ),
                (
                    "observation",
                    models.TextField(blank=True, verbose_name="Observacao"),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("all", "Todos"),
                            ("management", "Gestao"),
                            ("team", "Equipe"),
                            ("external_team", "Equipe Externa"),
                            ("private", "Privada"),
                        ],
                        default="all",
                        max_length=20,
                        verbose_name="Visibilidade",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="go_no_go_items",
                        to="cadastros.project",
                        verbose_name="Projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checklist Go/No-Go",
                "verbose_name_plural": "Checklists Go/No-Go",
                "ordering": ("project", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProjectOccurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Ocorrencia")),
                ("description", models.TextField(blank=True, verbose_name="Descricao")),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("all", "Todos"),
                            ("management", "Gestao"),
                            ("team", "Equipe"),
                            ("external_team", "Equipe Externa"),
                            ("private", "Privada"),
                        ],
                        default="all",
                        max_length=20,
                        verbose_name="Visibilidade",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_occurrences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occurrences",
                        to="cadastros.project",
                        verbose_name="Projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ocorrencia do projeto",
                "verbose_name_plural": "Ocorrencias do projeto",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ProjectOccurrenceAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Descricao do anexo"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=cadastros.models._project_occurrence_attachment_path,
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="cadastros.projectoccurrence",
                        verbose_name="Ocorrencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anexo da ocorrencia",
                "verbose_name_plural": "Anexos da ocorrencia",
            },
        ),
    ]
