# Generated by Django 5.2.6 on 2026-01-15

from django.db import migrations, models


def set_password_flags(apps, schema_editor):
    UserProfile = apps.get_model("cadastros", "UserProfile")
    UserProfile.objects.filter(user__last_login__isnull=False).update(
        must_change_password=False
    )
    UserProfile.objects.filter(user__last_login__isnull=True).update(
        must_change_password=True
    )


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0052_project_cutover_planned_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="must_change_password",
            field=models.BooleanField(
                default=True,
                verbose_name="Trocar senha no primeiro acesso",
            ),
        ),
        migrations.RunPython(set_password_flags, migrations.RunPython.noop),
    ]
