# Generated by Django 5.2.6 on 2026-01-25 13:45

import cadastros.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0053_userprofile_must_change_password"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "total_system",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total sistema"
                    ),
                ),
                (
                    "total_ofx",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total OFX"
                    ),
                ),
                (
                    "difference",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Diferenca"
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliations",
                        to="cadastros.companybankaccount",
                        verbose_name="Conta bancaria",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_reconciliations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Conciliado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conciliacao bancaria",
                "verbose_name_plural": "Conciliacoes bancarias",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="BankStatementImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=cadastros.models._bank_statement_import_path,
                        verbose_name="Arquivo OFX",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nome do arquivo"
                    ),
                ),
                (
                    "statement_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Inicio do extrato"
                    ),
                ),
                (
                    "statement_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fim do extrato"
                    ),
                ),
                (
                    "bank_id",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Banco OFX"
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Conta OFX"
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statement_imports",
                        to="cadastros.companybankaccount",
                        verbose_name="Conta bancaria",
                    ),
                ),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_statement_imports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Importado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Importacao OFX",
                "verbose_name_plural": "Importacoes OFX",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="BankStatementEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("posted_at", models.DateField(verbose_name="Data do movimento")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor"
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("credit", "Credito"), ("debit", "Debito")],
                        max_length=10,
                        verbose_name="Direcao",
                    ),
                ),
                (
                    "fit_id",
                    models.CharField(blank=True, max_length=120, verbose_name="FITID"),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Tipo OFX"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=120, verbose_name="Nome"),
                ),
                (
                    "memo",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Historico"
                    ),
                ),
                (
                    "check_number",
                    models.CharField(blank=True, max_length=60, verbose_name="Cheque"),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statement_entries",
                        to="cadastros.companybankaccount",
                        verbose_name="Conta bancaria",
                    ),
                ),
                (
                    "statement_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="cadastros.bankstatementimport",
                        verbose_name="Importacao OFX",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimento OFX",
                "verbose_name_plural": "Movimentos OFX",
                "ordering": ("-posted_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="BankSystemMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("movement_date", models.DateField(verbose_name="Data do movimento")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Descricao"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor"
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("credit", "Credito"), ("debit", "Debito")],
                        max_length=10,
                        verbose_name="Direcao",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("ofx", "Importado OFX")],
                        default="manual",
                        max_length=20,
                        verbose_name="Origem",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observacoes")),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_movements",
                        to="cadastros.companybankaccount",
                        verbose_name="Conta bancaria",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_system_movements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimento bancario",
                "verbose_name_plural": "Movimentos bancarios",
                "ordering": ("-movement_date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="BankReconciliationOfxItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor"
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("credit", "Credito"), ("debit", "Debito")],
                        max_length=10,
                        verbose_name="Direcao",
                    ),
                ),
                (
                    "reconciliation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ofx_items",
                        to="cadastros.bankreconciliation",
                        verbose_name="Conciliacao",
                    ),
                ),
                (
                    "ofx_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliation_items",
                        to="cadastros.bankstatemententry",
                        verbose_name="Movimento OFX",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conciliacao (OFX)",
                "verbose_name_plural": "Conciliacoes (OFX)",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("reconciliation", "ofx_entry"),
                        name="unique_reconciliation_ofx_entry",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BankReconciliationSystemItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor"
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("credit", "Credito"), ("debit", "Debito")],
                        max_length=10,
                        verbose_name="Direcao",
                    ),
                ),
                (
                    "payable_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliation_items",
                        to="cadastros.accountspayablepayment",
                        verbose_name="Pagamento",
                    ),
                ),
                (
                    "receivable_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliation_items",
                        to="cadastros.accountsreceivablepayment",
                        verbose_name="Recebimento",
                    ),
                ),
                (
                    "reconciliation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_items",
                        to="cadastros.bankreconciliation",
                        verbose_name="Conciliacao",
                    ),
                ),
                (
                    "system_movement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliation_items",
                        to="cadastros.banksystemmovement",
                        verbose_name="Movimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conciliacao (sistema)",
                "verbose_name_plural": "Conciliacoes (sistema)",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("receivable_payment__isnull", False),
                            ("payable_payment__isnull", False),
                            ("system_movement__isnull", False),
                            _connector="OR",
                        ),
                        name="bank_reconciliation_system_item_has_reference",
                    )
                ],
            },
        ),
    ]
