# Generated by Django 5.2.6 on 2026-01-25 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0054_bankreconciliation_bankstatementimport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="banksystemmovement",
            name="account_plan_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bank_system_movements",
                to="cadastros.accountplantemplateitem",
                verbose_name="Conta do plano de contas",
            ),
        ),
    ]
