# Generated by Django 5.2.6 on 2026-01-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0055_banksystemmovement_account_plan_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatGPTSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True,
                        help_text="Mensagem base enviada como role system.",
                        verbose_name="Prompt do sistema",
                    ),
                ),
                (
                    "analysis_prompt",
                    models.TextField(
                        blank=True,
                        help_text="Use {{PROJECT_CONTEXT}} e {{DETAILS_JSON}} para inserir os dados do projeto.",
                        verbose_name="Prompt da analise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parametros ChatGPT",
                "verbose_name_plural": "Parametros ChatGPT",
            },
        ),
    ]
