# Generated by Django 5.2.6 on 2026-01-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0056_chatgptsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatgptsettings",
            name="api_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Chave de acesso da API.",
                max_length=200,
                verbose_name="API Key",
            ),
        ),
        migrations.AddField(
            model_name="chatgptsettings",
            name="api_model",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ex.: gpt-4o-mini",
                max_length=120,
                verbose_name="Modelo",
            ),
        ),
        migrations.AddField(
            model_name="chatgptsettings",
            name="api_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ex.: https://api.openai.com/v1/chat/completions",
                max_length=200,
                verbose_name="API URL",
            ),
        ),
        migrations.AddField(
            model_name="chatgptsettings",
            name="org_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Header OpenAI-Organization (opcional).",
                max_length=120,
                verbose_name="Organization ID",
            ),
        ),
        migrations.AddField(
            model_name="chatgptsettings",
            name="project_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Header OpenAI-Project (opcional).",
                max_length=120,
                verbose_name="Project ID",
            ),
        ),
        migrations.AddField(
            model_name="chatgptsettings",
            name="request_timeout",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Tempo maximo de espera da requisicao.",
                null=True,
                verbose_name="Timeout (segundos)",
            ),
        ),
    ]
