# Generated by Django 5.2.6 on 2026-01-27 12:20

import cadastros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0057_chatgptsettings_api_key_chatgptsettings_api_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatementimport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=cadastros.models._bank_statement_import_path, verbose_name='Arquivo OFX'),
        ),
    ]
