# Generated by Django 5.2.6 on 2026-01-27 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0058_make_file_optional"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="accountspayablepayment",
            index=models.Index(
                fields=["bank_account", "payment_date"],
                name="cadastros_a_bank_ac_1c6efd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accountsreceivablepayment",
            index=models.Index(
                fields=["bank_account", "payment_date"],
                name="cadastros_a_bank_ac_fcc83b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bankstatemententry",
            index=models.Index(
                fields=["bank_account", "posted_at"],
                name="cadastros_b_bank_ac_22756d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="banksystemmovement",
            index=models.Index(
                fields=["bank_account", "movement_date"],
                name="cadastros_b_bank_ac_a42aef_idx",
            ),
        ),
    ]
