"""
Django settings for pmorganizer project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file for local development
load_dotenv(BASE_DIR / ".env")
# coment novo

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-lp%gi(9!p-(rc#=)uafmi3c9k_xvp#)gb_9g6tcj@1m*mk7)rw"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"

# Allow Vercel domains and configured hosts
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
# Add Vercel domain pattern
if ".vercel.app" in os.environ.get("VERCEL_URL", ""):
    ALLOWED_HOSTS.append(".vercel.app")
# Add all Vercel domains in production
if not DEBUG:
    ALLOWED_HOSTS.extend([".vercel.app", "*"])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "cadastros.apps.CadastrosConfig",
    "rest_framework",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Add WhiteNoise
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "cadastros.middleware.ForcePasswordChangeMiddleware",  # Force password change on first login
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "pmorganizer.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "cadastros.context_processors.user_role",
            ],
        },
    },
]

WSGI_APPLICATION = "pmorganizer.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use DATABASE_URL if provided, otherwise fallback to SQLite for local development
DATABASE_URL = os.environ.get("DATABASE_URL")
if DATABASE_URL:
    raw_database_url = DATABASE_URL.strip()
    if "://" not in raw_database_url:
        # Some providers return host-style strings without scheme.
        DATABASE_URL = f"postgresql://{raw_database_url}"
    else:
        scheme, rest = raw_database_url.split("://", 1)
        # Prisma-style URLs can set the hostname as "scheme" (e.g. db.prisma.io).
        if "." in scheme and scheme not in {"postgres", "postgresql"}:
            DATABASE_URL = f"postgresql://{rest}"
        else:
            DATABASE_URL = raw_database_url

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    # Fallback to SQLite for local development
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True

USE_THOUSAND_SEPARATOR = True
DECIMAL_SEPARATOR = ","
THOUSAND_SEPARATOR = "."
NUMBER_GROUPING = 3

DATE_FORMAT = "d/m/Y"
DATETIME_FORMAT = "d/m/Y H:i"
TIME_FORMAT = "H:i"
DATE_INPUT_FORMATS = ["%d/%m/%Y"]
DATETIME_INPUT_FORMATS = ["%d/%m/%Y %H:%M"]
TIME_INPUT_FORMATS = ["%H:%M"]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "assets"]
STATIC_ROOT = BASE_DIR / "staticfiles"  # For collectstatic

# WhiteNoise configuration for efficient static file serving
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
WHITENOISE_USE_FINDERS = True
WHITENOISE_MANIFEST_STRICT = False
WHITENOISE_ALLOW_ALL_ORIGINS = True

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

LOGIN_URL = "/area-restrita/login/"
LOGIN_REDIRECT_URL = "/app/"
LOGOUT_REDIRECT_URL = "/"
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "PAGE_SIZE_QUERY_PARAM": "page_size",
    "MAX_PAGE_SIZE": 200,
    "DEFAULT_FILTER_BACKENDS": (
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
}

OPPORTUNITIES_API_URL = os.environ.get(
    "OPPORTUNITIES_API_URL",
    "https://seniorconnect.com.br:9010/fast-prod/workflowrest/demandas-abertas-consultorias",
)
OPPORTUNITIES_API_TOKEN = os.environ.get(
    "OPPORTUNITIES_API_TOKEN",
    "K06zKSYhC4r69zNcul3QGmaXSUnOCaxI",
)
OPPORTUNITIES_REFRESH_DEFAULT = int(
    os.environ.get("OPPORTUNITIES_REFRESH_DEFAULT", "120")
)
OPPORTUNITIES_REFRESH_MIN = int(
    os.environ.get("OPPORTUNITIES_REFRESH_MIN", "30")
)
OPPORTUNITIES_REQUEST_TIMEOUT = int(
    os.environ.get("OPPORTUNITIES_REQUEST_TIMEOUT", "15")
)

RECEITA_FEDERAL_API_URL = os.environ.get(
    "RECEITA_FEDERAL_API_URL",
    "https://brasilapi.com.br/api/cnpj/v1/",
)
RECEITA_FEDERAL_REQUEST_TIMEOUT = int(
    os.environ.get("RECEITA_FEDERAL_REQUEST_TIMEOUT", "15")
)
RECEITA_FEDERAL_USER_AGENT = os.environ.get(
    "RECEITA_FEDERAL_USER_AGENT",
    "PMOrganizer",
)

CHATGPT_API_URL = os.environ.get(
    "CHATGPT_API_URL",
    "https://api.openai.com/v1/chat/completions",
)
CHATGPT_API_KEY = os.environ.get(
    "CHATGPT_API_KEY",
    "",
)
CHATGPT_ORG_ID = os.environ.get("CHATGPT_ORG_ID", "")
CHATGPT_PROJECT_ID = os.environ.get("CHATGPT_PROJECT_ID", "")
CHATGPT_MODEL = os.environ.get("CHATGPT_MODEL", "gpt-4o-mini")
CHATGPT_REQUEST_TIMEOUT = int(
    os.environ.get("CHATGPT_REQUEST_TIMEOUT", "25")
)

# WhatsApp Z-API Configuration
WHATSAPP_ZAPI_INSTANCE_ID = os.environ.get("WHATSAPP_ZAPI_INSTANCE_ID", "")
WHATSAPP_ZAPI_TOKEN = os.environ.get("WHATSAPP_ZAPI_TOKEN", "")
WHATSAPP_ZAPI_CLIENT_TOKEN = os.environ.get("WHATSAPP_ZAPI_CLIENT_TOKEN", "")
WHATSAPP_ZAPI_BASE_URL = os.environ.get("WHATSAPP_ZAPI_BASE_URL", "https://api.z-api.io")
WHATSAPP_ZAPI_TIMEOUT = int(os.environ.get("WHATSAPP_ZAPI_TIMEOUT", "15"))
WHATSAPP_ZAPI_LOG_REQUESTS = os.environ.get("WHATSAPP_ZAPI_LOG_REQUESTS", "true").lower() in (
    "1",
    "true",
    "yes",
)

# Logging Configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        "cadastros.whatsapp_client": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "cadastros.web_views": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
